PartyID: 2

General:
  ListenAddress: 0.0.0.0
  ListenPort: 7150
  TLS:
    Enabled: true
    PrivateKey: /node-tls/server.key
    Certificate: /node-tls/server.crt
    # clients are trusted via the application orgs' TLS CAs in the genesis block (more: ClientRootCAs)
    ClientAuthRequired: true
  Bootstrap:
    Method: block
    File: /bootstrap/genesis.block
  LocalMSPDir: /node-msp
  LocalMSPID: OrdererOrg2MSP

  # Validate client signatures against /Channel/Writers. Needed on the router (client-facing) and
  # on the batcher (re-verifies batches from other parties' primaries); not on the consenter.
  ClientSignatureVerificationRequired: true

FileStore:
  Location: /data

Operations:
  ListenAddress: 0.0.0.0
  ListenPort: 9443
  TLS:
    Enabled: false

Router:
  NumberOfStreamsPerConnection: 20
