PartyID: 1

General:
  ListenAddress: 0.0.0.0
  ListenPort: 7053
  TLS:
    Enabled: true
    PrivateKey: /node-tls/server.key
    Certificate: /node-tls/server.crt
    # clients are trusted via the application orgs' TLS CAs in the genesis block (more: ClientRootCAs)
    ClientAuthRequired: true
  Bootstrap:
    Method: block
    File: /bootstrap/genesis.block
  Cluster:
    ClientCertificate: /node-tls/server.crt
    ClientPrivateKey: /node-tls/server.key
  LocalMSPDir: /node-msp
  LocalMSPID: OrdererOrg1MSP

FileStore:
  Location: /data

Operations:
  ListenAddress: 0.0.0.0
  ListenPort: 9443
  TLS:
    Enabled: false

# all defaults
Assembler: {}
